apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBhyFjprkO7zSr6yqpTUkYlXOuUYByHt9N3cIoHHF07DChXo21nYe+t4e8mzoCT3ohoRTTSy4oyqOjzel/KRWAyk5/xyJYmLxONlzWKEq/EOEar8jF/+RGh51ByxxMbolVRLQDnucZc0QZWp7VxDKC2MEAEhBU++bld6HkIlfIgIR7tSGGsDhqaoOpF/8wK8M9k3cDDBHnxA282MhwmdmzhTeHEdJwBKqH8Wz1LacVzRsmi8yjfS6VOwrWppaF7Q9sO9OZUYsW7SqpqKiPi+qEALGePz1kv+K2h0I5yrZPuajNm8hKd5hjuy/oKMWSBNfW977dqlZlNdA2mkEJSaWzvOxRlH6ivx8ee1ZiY+T3IwUvWHH0HiUB02jEgkIANIj6n6gB/JaDRcc28imRFwouirgFNi5LUfAMAK0k9go4gvuIXNaHbn646kzNP3xLQAC6tKrwuakV2fjkhQN3tW6MYwKwvtHIjWWcDtaJfxbcAo+E5hVhBvKREAkPNF2E330JTQBgygUeIm4rcxRshRciLsyexELd7eTl1iwELJNCNHsGQzhMQ9fZrBx7//jR1O87evmb79E7REYr8u32e3tA9K49xuhlX0Wb/1jrxZv5tDoSUoxus77/TxWvJER2cLmszRxhD2LDDoKF8woyjl8sM8ZOysHCBFarapePXxjvgfkI+ieW5GXKgqWYXClOARshAAiz81G1mHn4nXTRJKUHVtXcBiUiutl7pvQuCLdGb7dDZ08x1DJR0SngFqz9JiRA9YxgoAkDeL/5Zgv/jNugVWnheyr0MT/mdYnqXEtBO+ogbJ3mT2oFSX1QUw/KVuXhEAoM1FbSdiuAIiiKb0tyRUFlr3tpkGqrV/tHxOGF/va2oshWGz3NXmaoHMWyxNT5vkpM+0rRvbTi+dzyQl3i99jtOqe1Bb2lCT7+X+tK/WQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

