apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAPO2gPHnYbIKyxujkqWHNYs4YXA7F7cIVZKEkRJFcjg0U7H8Rgk9oQ6TT2Nhtf9avYM0XcCx19ObVikiThAsFe8AYqDXvlq9OI2ooiXCPwcseeOitdFa+gSj2FNu3CzVbhqT9Hfe4+8IHggCZtP8nYVnbs7HYPJujqDpWK+QGW3xRjlIITTHQw7olWdRiROrVOXPQ0MKqMFu06JA0FgHVoDpZuWZMIWd7UJUXIXaG/5Cy6sFXSLKh7EZORy733Zb9GVIlemJNa4QB0SyV1tTJXy6FcoJEMzuGDWpNvjVLB1yfMAXTIWWGNIJ99v1m5p4qLks90XSynPPfGSDwKQnkwvgnGLxspES16rqSY3+hZKcgiB9e8RlCOWF8Z2PBisfI5O709LzG5ecRaUvE4g7bnQMUsCtGYBnO5P3gUX/x/yODRMaa5oAE8ZFyMLE5Rmt0elRHpoYxv3eXV8UCuD0RX1MkxLX6sa9rJuNN0FtkCMlwAoYgK4A4+4z+DZAvwdgFJt2Ny3ArbM7Z18OaL/3Ho+msJqpT2pGKs0aZ2tDmqPZwI7sYIyr7A6aWpj73n/ulZAHrQsq1hmy4rcPO4RK8u2Rkcret9MSnul4czdTbR3yBCwmbfKJH8ROZHELMKquxYL/pq0Wm2h6hzgh6ph8oE68TqxRtJh84Ic6j39r/s3sY7Ee8cpwMdk/2NnSrweOcc3UlcorJOeUghkzlJDbMgGdTanUuSzwWrQ0yYzy/Ez2tMZopFnKFNngHz/q5pZEEcNzxvsrPGaLtNagltqwvefnn5SxyDc2YxCHXzxjkNXbnX9UQ2MSaC5Mwlh4bIgUeS2yCCsbqQvY7EASQOs+AWBFbW0Rx11uuamOstwu7dbpzvsjuhurupXFaguUVU+Tn62SSH0QE+EIYLBc6zmnOcNHEP7Zpg9LO4ZTQNziKIvw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

