apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBIFuvh8CXVEgsIfKRPjU+q+nh+wI9ck2RaI+dxgRAXIIeBM6KmlZxTXmOtJKHF61Asf1AJIk6+x6mcBVlwXsWXLIiHw3vRN90wJ20gC61+Hz1d6En7Pa+kc4w0HTZbIcGpcT+W36k3Uwg/If0BksG1ZeysvVQ7Q5UxhDcv1SatX62mCFjEMm8CqTLg9p3+yZYEV1GkKBLB7exh3kDAsV+8zagpNRZ3LPAck7XZQKwuVP76HS3mibA0dgDEBqAo7vkhRRIneqU5XJFRBBs7nbj/Ekm27Br/jUkfGXWj7wyj/UkEQ6NXpPIlcZrTo+sL54Ckk7G6sWpxmVMGm3WDeSCqwV/K5wmJjj+qNSjIwzeIiW22FYVb7sk2Q16VmLKpSmo2V4WMeCTRKvssFjjxMxez63xfR34Ty/FealDdY7DeagLhuGziG116c3SSpk+YEEvajIccOll500lCYVHB1Tpd/uR8JzhpAQP5fjoaMhXNo3jiNzpWZJQo8sBOmdhGSwu3AQo/5GE6l4MRlmwV66fm5TlE8Fd1TCnY6urdy+ZCRDYBLBVd6atqGoY27jk9Hi8lBwD2v7OA8orye8rValNg2eKJRomkq9kxGW6RUkgd9OU+Wajyn4rJ9w5tp0WSnptaUtIdTL20k9Omp6BfBQrc84+MLD30UVWIGE3DXxY6pALCd96t+B/8nfOauwMfn8HcyVxEvaSjKVL+GRUNmRzPz6ctwopIikel6YKhAkN3tyRXslFcc+53
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

