apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAMPGTzF9cT/vR7aJtiNMm4+oz9EQx3xZlHDAK1QPPGhQ3kWslPlSJ6ICJJxE9QVXlRakOI7lerEfKFuvpcTMsU/0EO7N8MN/e8hs1xrdvTrwO/mp3evu38OcRuTV+F7rdlvsUYzqpUkJgQsptXZTcq5y5EkjEsR8DrMQrfilGmN6TD5WlLLyGWWK67uoM3yDLiyiDhU02xzqFaxLQq8Zye1n7KvhHyvy0nYkcJpYPjnc3YVkM2RBiEdBJzrY084DuEZKY2ENkc7+0TZqAGSqg9N5IO1zCX82t6adr3HOwiJV3SMH0+DL/+UQqYJQIs09NYBfjw8ESJI38p6qXyGUeuQQgyTVrY7UfnJheOVeglDF/ZuSYhowUdcvnbvmcbKdJXDl8cH/IbjFTJ4xe71+kkrvtT/VcjCRcn5P8sDkdsjcihfVix/CHsUxSBrRDjs9vUI24f9hynzpzTzRpNFG/H884IRwI1NxLUwuiUFPVxUXPsNe6MOczi4aErxoSqfbqfZ1hi2rj9AxOeZPtnFGEu7K6AcmU67pyCO5+VliYjK/1ZlyDGw8A4/zf2j/tSiO7Sf7gVN2/ZkUoGTKi+Z0tRU6tsYjZ5G7oFjt3kS0xYPgR1SJlnwDFuwjJmUJPEHlxMZQm+DkxeRl6cC304OdwbR7bWdXwtQVTh+8RCQViNHOwYYWTxUe4nJkwSKCNv4cEwEIaylp0mslyTxP514wQfDVUVnMd4hckmqvRROA4PBfiK1CdJBJVG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

